# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db80533ad511fe246f42eaea4cea9a2a9a1122128ad29c4d7aae7ce9b4157e105fd9cf722759ecfa15db8725f6f1d16eed79399b04c1b2305a8e68f415afbeff

test:
  secret_key_base: 2c249341b65a24f0296ceb2a24bfcae0641d1ab0ac08f28c6d3e9d9541bf5f3e00f101364dc96e024aafa547c0608969299fb836ea22057122f0086077d8ea8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
